name: CI/CD Pipeline

on:
  push:
    branches: [ main,feature/ci-cd-pipeline, feature/security  ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          pip install pytest
      
      - name: Run tests
        run: pytest tests/ || echo "No tests yet"
      
  security-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Bandit (SAST for Python)
        run: |
          pip install bandit
          bandit -r src/ -f json -o bandit-report.json || true
      
      - name: Upload SAST results
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: bandit-report.json


  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t todo-api .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
         docker tag todo-api ${{ secrets.DOCKER_USERNAME }}/todo-api:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:latest

  security-dast:
            needs: build
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v4

                # Build et lancer le conteneur de l'application
                - name: Build Docker image
                  run: docker build -t todo-api .

                - name: Start application
                  run: docker run -d -p 5000:5000 --name todo-api todo-api

                # Attendre que l'application soit disponible
                - name: Wait for app
                  run: |
                    for i in {1..10}; do
                    if curl -s http://localhost:5000; then
                        echo "App is up"
                        break
                    fi
                    echo "Waiting for app..."
                    sleep 3
                    done

                # Lancer ZAP
                - name: Run OWASP ZAP Baseline Scan
                  run: |
                    docker run -t --rm -v ${{ github.workspace }}:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable \
                    zap-baseline.py -t http://localhost:5000 -r /zap/wrk/zap-report.html -J /zap/wrk/zap-report.json

                # Upload des reports
                - name: Upload ZAP report
                  uses: actions/upload-artifact@v4
                  with:
                    name: dast-report
                    path: |
                     zap-report.html
                     zap-report.json
